services:
  finstack-db:
    image: bitnami/postgresql:latest
    container_name: finstack-db
    environment:
      POSTGRESQL_DATABASE: finstack_db
      POSTGRESQL_PASSWORD: secretpass
      POSTGRESQL_USERNAME: rxman
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finstack_network
    restart: always

  finstack-app-api:
    build:
      dockerfile: Dockerfile
    container_name: finstack-app-api
    depends_on:
      - finstack-db
    env_file: # <--- Option A: Explicitly tell it to use the .env file
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE={DEPLOYMENT}
      - SPRING_DATASOURCE_URL={DB_URL}
      - SPRING_DATASOURCE_USERNAME={DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD={DB_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET_KEY=${GOOGLE_SECRET_KEY}
    ports:
      - "8080:8080"
    networks:
      - finstack_network
    restart: unless-stopped

volumes:
  postgres_data:
networks:
  finstack_network:
    driver: bridge
