services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: budgets_db
      POSTGRESQL_PASSWORD: secretpass
      POSTGRESQL_USERNAME: rxman
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget_network
    restart: always

  budget-app:
    build:
      dockerfile: Dockerfile
    container_name: budget-app
    depends_on:
      - postgres
    env_file: # <--- Option A: Explicitly tell it to use the .env file
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/budgets_db
      - SPRING_DATASOURCE_USERNAME=rxman
      - SPRING_DATASOURCE_PASSWORD=secretpass
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET_KEY=${GOOGLE_SECRET_KEY}
    ports:
      - "8080:8080"
    networks:
      - budget_network
    restart: unless-stopped



volumes:
  postgres_data:
networks:
  budget_network:
    driver: bridge
