server:
  port: 8080
  servlet:
    context-path: /api/v1
application:
  security:
    jwt:
      secret-key: dGVzdF9zZWNyZXRfcGFzcwo=
      expiration: 900000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5444/budgets_db
    username: rxman
    password: secretpass
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - openid
              - profile
              - email
logging:
  level:
    org:
      springframework:
        security: DEBUG
