server:
  port: 8080
  servlet:
    context-path: /api/v1
application:
  security:
    jwt:
      secret-key: bXktc3VwZXItc2VjcmV0LWp3dC1rZXktdGhhdC1pcy1sb25nLWVub3VnaC1mb3ItMjU2LWJpdHMtc2VjdXJpdHktcmVxdWlyZW1lbnQ=
      expiration: 86_400_000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/budgets_db
    username: rxman
    password: secretpass
  jpa:
    hibernate:
      ddl-auto: validate
    show_sql: false
    properties:
      hibernate.format_sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - openid
              - profile
              - email
logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    tags-sorter: none   # use 'none' to preserve order defined in the spec
    doc-expansion: list
